services:
  db:
    image: postgres:16
    container_name: postgres
    env_file: .env.docker
    volumes:
      - pgdata:/var/lib/postgresql/data

  web: # 🌐 Обратный прокси
    build: .    #это значит ищи один докерфайл в корне проекта и собирай его
    image: django:1.0  #image используется тут, чтобы назвать наш образ
    container_name: django
    volumes: # директории и так скопируются в контейнер, но если volumes не прокидывать то обновления кода при перезапуске
      # не будет, потому что таким образом наш код связан с кодом внутри контейнера
      - ./app:/app/app
      - ./cart:/app/cart
      - ./fixtures:/app/fixtures
      - ./goods:/app/goods
      - ./main:/app/main
      - ./nginx:/app/nginx
      - ./orders:/app/orders
      - ./templates:/app/templates
      - ./users:/app/users
      - ./manage.py:/app/manage.py
      - ./requirements.txt:/app/requirements.txt
      - static:/app/staticfiles   # оно сохраняет всё что в staticfiles, в папке внутри контейнера, и при перезапуске всё сохраняется
      - ./media:/app/media
    env_file: .env.docker
    ports:
      - "8000:8000"
    depends_on:
      - db

  celery:
    image: django:1.0  #берём сразу образ основного приложения, чтобы не билдить снова
    container_name: celery
    command: celery -A app worker --loglevel=info
    volumes: # директории и так скопируются в контейнер, но если volumes не прокидывать то обновления кода при перезапуске
      # не будет, потому что таким образом наш код связан с кодом внутри контейнера
      - ./app:/app/app
      - ./cart:/app/cart
      - ./goods:/app/goods
      - ./main:/app/main
      - ./orders:/app/orders
      - ./users:/app/users
      - ./manage.py:/app/manage.py
    env_file: .env.docker
    depends_on:
      - web
      - redis


  nginx:
    image: nginx:1.25
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default:/etc/nginx/conf.d/default.conf   # это настройки nginx, если их не прокинуть, то будет апокалипсис
      - static:/app/staticfiles   # тут оно само видит статику и перемещает всю её в контейнер. nginx нужен доступ к staticfiles, чтобы оттуда всё раздавать (тот же volume в nginx).
      - ./media:/app/media        # тут оно отвечает, из какой папки куда ты кладёшь всё из моей в контейнера,(загружаемые пользователем файлы)
    depends_on: # если есть с начала ./, то не надо прокидывать в volumes в конце
      - web


  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6380:6379"  # первый порт это на мой комп прокидывается, чтобы локальный редис не пересекался
    volumes:
      - redis_data:/data
    depends_on:
      - web


  flower:
    image: mher/flower:0.9.7
    container_name: flower
    command: flower --port=5555 --broker=redis://redis:6379/0
    ports:
      - '5555:5555'
    depends_on:
      - web
      - redis
volumes:
  pgdata:      # Volume для хранения данных PostgreSQL
  static:      # Volume для хранения статических файлов Django, используется и web, и nginx
  redis_data:  # для хранения данных редиса, иначе докер не даст создать контейнер, где-то же надо хранить данные
