"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 4.2.19.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
from pathlib import Path


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-=%2j#7bp$0_3eqantsmcmxkw*+bd95gh4r(m5jx-lmqbu$y!+7'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*'] # поставь звёздочку, тебе что жалко что ли?


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.postgres',

    'main',
    'goods',
    'users',
    'cart',
    'orders',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates' ], #Это чтобы оно видело в корне папку BASE DIR это корень проекта, а templates директория в корне
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'app.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'django_postgres',
        'HOST': 'localhost',
        'PASSWORD': 'p',
        'USER': 'new',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'Europe/Minsk'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
] #это чтобы django знал что надо искать в static

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'users.User' #благодаря этому мы переопределили модель auth в users.models

MEDIA_URL ='/media/'
MEDIA_ROOT = BASE_DIR / 'media' #это чтобы работало добавление и взятие картинок из goods_images

LOGIN_URL = '/users/login/' # это чтобы когда ты не зашёл в акк то если ты пытаешься зайти на страницу где он нужен чтобы login required переслал тебя на ту что указана

# EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
# EMAIL_HOST = "smtp.gmail.com"
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_FROM = "mydjango111@gmail.com"
# EMAIL_HOST_USER = "mydjango111@gmail.com"
# EMAIL_HOST_PASSWORD = "aaoaifhebrtutooz" # пароль сгенерированный в gmail почте там где пароли приложения




#как писать тесты в проекте максимально эффективно и вообще тут их писать
#как писать тесты в проекте максимально эффективно и вообще тут их писать
#как писать тесты в проекте максимально эффективно и вообще тут их писать
#как писать тесты в проекте максимально эффективно и вообще тут их писать
#как писать тесты в проекте максимально эффективно и вообще тут их писать
#как писать тесты в проекте максимально эффективно и вообще тут их писать
#как писать тесты в проекте максимально эффективно и вообще тут их писать
#как писать тесты в проекте максимально эффективно и вообще тут их писать
#как писать тесты в проекте максимально эффективно и вообще тут их писать
#как писать тесты в проекте максимально эффективно и вообще тут их писать
#как писать тесты в проекте максимально эффективно и вообще тут их писать
#как писать тесты в проекте максимально эффективно и вообще тут их писать
#как писать тесты в проекте максимально эффективно и вообще тут их писать
#как писать тесты в проекте максимально эффективно и вообще тут их писать
#как писать тесты в проекте максимально эффективно и вообще тут их писать
#как писать тесты в проекте максимально эффективно и вообще тут их писать
#как писать тесты в проекте максимально эффективно и вообще тут их писать